# Generated by Django 5.0.6 on 2024-07-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(default='https://cdn-icons-png.flaticon.com/512/1178/1178479.png'),
        ),
    ]
